# 배열의 연산

In [2]:
import numpy as np

x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [4]:
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [5]:
z = x + y
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [7]:
np.all(a == c)

True

In [8]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [9]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [11]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [12]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [14]:
x = np.arange(12).reshape(3, 4) # 생성 후 바로 변환
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [17]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [18]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [19]:
x + y

array([1, 2, 3, 4, 5])

In [20]:
x + 1

array([1, 2, 3, 4, 5])

In [36]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [37]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [38]:
y.shape

(5, 1)

In [39]:
x. shape

(5, 3)

In [40]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [41]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [42]:
np.sum(x)

10

In [43]:
x = np.array([1, 3, 2])

In [44]:
x.min()

1

In [45]:
x.sum()

6

In [46]:
x = np.array([1, 2, 3, 1])

In [47]:
x.mean()

1.75

In [49]:
np.median(x)

1.5

In [50]:
a = np.zeros((100, 100), dtype=np.int)
a

C:\Users\admin\AppData\Local\Temp\ipykernel_17084\2477046962.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.zeros((100, 100), dtype=np.int)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [51]:
np.any(a != 0)

False

In [52]:
np.all(a == 0)

True

In [53]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [54]:
x.sum(axis = 1)

array([2, 4])

In [56]:
x.sum(axis= 0)

array([3, 3])

In [57]:
x = np.array(range(30)).reshape(5,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
x.sum()

435

In [60]:
x.sum(axis=1)

array([ 15,  51,  87, 123, 159])

In [61]:
x.max(axis=1)

array([ 5, 11, 17, 23, 29])

In [62]:
x.mean(axis=0)

array([12., 13., 14., 15., 16., 17.])

In [63]:
x.min(axis=0)

array([0, 1, 2, 3, 4, 5])

In [64]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [65]:
np.sort(a)

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [66]:
np.sort(a, axis=0) # 각 행 정렬

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [67]:
a.sort(axis=1) # 각 열 정렬

In [73]:
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
type(a)

numpy.ndarray

In [84]:
eng_rank = a.argsort(axis = 1)[1]
eng_rank

array([0, 3, 1, 2], dtype=int64)

In [95]:
a = a[:,eng_rank]

In [96]:
a

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [104]:
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

In [105]:
math_rank = a.argsort()[2]
math_rank

array([1, 0, 2, 3], dtype=int64)

In [107]:
a = a[:,[1, 0, 2, 3]]
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])