# 넘파이 배열

In [1]:
import numpy as np

In [2]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

In [4]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
answer = []
for di in data:
    answer.append(2 * di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [6]:
x = np.array(data)

In [7]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
2 * x        # 벡터화 연산

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [10]:
2 * a + b

array([12, 24, 36])

In [11]:
a == 2

array([False,  True, False])

In [12]:
c = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array
c

array([[0, 1, 2],
       [3, 4, 5]])

In [14]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [15]:
d = np.array([[[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]],
             [[11, 12, 13, 14],
             [15, 16, 17, 18],
             [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [16]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [17]:
d.ndim

3

In [18]:
d.shape

(2, 3, 4)

In [19]:
a.ndim

1

In [20]:
b.ndim

1

In [21]:
c.ndim

2

In [22]:
c.shape

(2, 3)

In [23]:
a = np.array([0, 1, 2, 3, 4])

In [24]:
a[2]

2

In [25]:
a[-1]

4

In [27]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [28]:
a[1,1]

4

In [29]:
a[-1, -1]

5

In [30]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
a[0,:]

array([0, 1, 2, 3])

In [34]:
a[:, 1]

array([1, 5])

In [35]:
a[1, :]

array([4, 5, 6, 7])

In [36]:
a[1,1:]

array([5, 6, 7])

In [52]:
m = np.array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9],
            [10, 11, 12, 13, 14]])

In [53]:
m[1,2]

7

In [54]:
m[2,-1]

14

In [55]:
m[-1,-1]

14

In [56]:
m[1,1:3]

array([6, 7])

In [57]:
m[1:3, 2]

array([ 7, 12])

In [58]:
m[0:2,3:]

array([[3, 4],
       [8, 9]])

In [60]:
m[:-1, 3:]

array([[3, 4],
       [8, 9]])

In [61]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [62]:
a % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [63]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [64]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array(a%2 == 0)
a[idx]

array([0, 2, 4, 6, 8])

In [65]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [66]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [83]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [84]:
idx = np.array(x % 3 == 0)
x[idx]

array([ 3,  6,  9, 12, 15, 18])

In [85]:
idx = np.array(x % 4 == 1)
x[idx]

array([ 1,  5,  9, 13, 17])

In [90]:
idx = np.array((x % 3 == 0) & (x % 4 ==1))
x[idx]

array([9])